---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name }}
{{ include "commons.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        deploymentconfig: {{ .Values.name }}
{{ include "commons.labels" . | indent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - image:  {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.environment }}
          envFrom:
            - secretRef:
                name: dummy-project-secret
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: {{ .Values.name }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: external-registry
      volumes:
        - name: dummy-project-secret
          secret:
            secretName: dummy-project-secret