---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
{{ include "commons.labels" . | indent 4 }}
  name: {{ .Values.name }}
spec:
  ports:
    - name: 80-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
